2018-10-03 13:27:06.616 +01:00 [ERR] (node:11452) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
2018-10-03 13:38:52.966 +01:00 [ERR] (node:6532) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
2018-10-03 13:40:59.024 +01:00 [ERR] (node:11268) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
2018-10-03 14:00:50.833 +01:00 [ERR] (node:12572) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
2018-10-03 14:33:53.185 +01:00 [ERR] (node:18092) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
2018-10-03 14:57:50.776 +01:00 [ERR] ├ù ∩╜ówdm∩╜ú: Hash: 5257e93e9ae100ebb9f6
Version: webpack 4.20.2
Time: 12630ms
Built at: 2018-10-03 14:57:50
                                             Asset       Size       Chunks             Chunk Names
                                    main-client.js   3.07 MiB  main-client  [emitted]  main-client
    main-client.5fa5b73e855ba7185b3a.hot-update.js   11.8 KiB  main-client  [emitted]  main-client
              5fa5b73e855ba7185b3a.hot-update.json   53 bytes               [emitted]  
                                main-client.js.map   29.9 KiB  main-client  [emitted]  main-client
main-client.5fa5b73e855ba7185b3a.hot-update.js.map  123 bytes  main-client  [emitted]  main-client
Entrypoint main-client = main-client.js main-client.5fa5b73e855ba7185b3a.hot-update.js main-client.js.map main-client.5fa5b73e855ba7185b3a.hot-update.js.map

ERROR in [at-loader] ./ClientApp/app/components/services/codesetstatistics.service.ts:187:21 
    TS2552: Cannot find name 'tmp'. Did you mean 'tmpI'?
2018-10-03 17:39:55.235 +01:00 [ERR] ├ù ∩╜ówdm∩╜ú: Hash: c304b49e75a5ace229e3
Version: webpack 4.20.2
Time: 12590ms
Built at: 2018-10-03 17:39:55
                                             Asset       Size       Chunks             Chunk Names
                                    main-client.js   3.07 MiB  main-client  [emitted]  main-client
    main-client.36f52c72069fc1f9dce2.hot-update.js   14.3 KiB  main-client  [emitted]  main-client
              36f52c72069fc1f9dce2.hot-update.json   53 bytes               [emitted]  
                                main-client.js.map   29.9 KiB  main-client  [emitted]  main-client
main-client.36f52c72069fc1f9dce2.hot-update.js.map  123 bytes  main-client  [emitted]  main-client
Entrypoint main-client = main-client.js main-client.36f52c72069fc1f9dce2.hot-update.js main-client.js.map main-client.36f52c72069fc1f9dce2.hot-update.js.map

ERROR in [at-loader] ./ClientApp/app/components/services/codesetstatistics.service.ts:181:17 
    TS2447: The '&' operator is not allowed for boolean types. Consider using '&&' instead.
2018-10-03 17:40:11.018 +01:00 [ERR] Dataportal error
2018-10-03 17:40:11.020 +01:00 [ERR] MSG: DataPortal.Fetch failed (Logon ERROR: current logon ticket is not valid.)
2018-10-03 17:40:11.022 +01:00 [ERR] STACK TRC:   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewSetsList.DataPortal_Fetch() in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewSetsList.cs:line 278
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object criteria)
   at ERxWebClient2.Controllers.CodesetController.CodesetsByReview() in D:\Github\eppi\ERCentralAPI\ERxWebClient2\Controllers\CodesetController.cs:line 38
2018-10-03 17:40:11.022 +01:00 [ERR] Inner Exception(s): 
2018-10-03 17:40:11.022 +01:00 [ERR] MSG(1): ReviewSetsList.DataPortal_Fetch method call failed
2018-10-03 17:40:11.027 +01:00 [ERR] STACK TRC(1):   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewSetsList.DataPortal_Fetch() in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewSetsList.cs:line 278
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
2018-10-03 17:40:11.027 +01:00 [ERR] MSG(2): Logon ERROR: current logon ticket is not valid.
2018-10-03 17:40:11.028 +01:00 [ERR] STACK TRC(2):   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewSetsList.DataPortal_Fetch() in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewSetsList.cs:line 278
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
2018-10-03 17:40:11.999 +01:00 [ERR] An unhandled exception has occurred while executing the request
Csla.DataPortalException: DataPortal.Fetch failed (Logon ERROR: current logon ticket is not valid.) ---> Csla.Reflection.CallMethodException: ReviewSetsList.DataPortal_Fetch method call failed ---> System.Exception: Logon ERROR: current logon ticket is not valid.
   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewSetsList.DataPortal_Fetch() in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewSetsList.cs:line 278
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   --- End of inner exception stack trace ---
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object criteria)
   at ERxWebClient2.Controllers.CodesetController.CodesetsByReview() in D:\Github\eppi\ERCentralAPI\ERxWebClient2\Controllers\CodesetController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

2018-10-03 17:40:12.685 +01:00 [ERR] Dataportal error
2018-10-03 17:40:12.685 +01:00 [ERR] MSG: DataPortal.Fetch failed (Logon ERROR: current logon ticket is not valid.)
2018-10-03 17:40:12.695 +01:00 [ERR] STACK TRC:   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewSetsList.DataPortal_Fetch() in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewSetsList.cs:line 278
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object criteria)
   at ERxWebClient2.Controllers.CodesetController.CodesetsByReview() in D:\Github\eppi\ERCentralAPI\ERxWebClient2\Controllers\CodesetController.cs:line 38
2018-10-03 17:40:12.695 +01:00 [ERR] Inner Exception(s): 
2018-10-03 17:40:12.695 +01:00 [ERR] MSG(1): ReviewSetsList.DataPortal_Fetch method call failed
2018-10-03 17:40:12.695 +01:00 [ERR] STACK TRC(1):   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewSetsList.DataPortal_Fetch() in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewSetsList.cs:line 278
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
2018-10-03 17:40:12.695 +01:00 [ERR] MSG(2): Logon ERROR: current logon ticket is not valid.
2018-10-03 17:40:12.705 +01:00 [ERR] STACK TRC(2):   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewSetsList.DataPortal_Fetch() in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewSetsList.cs:line 278
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
2018-10-03 17:40:13.327 +01:00 [ERR] An unhandled exception has occurred while executing the request
Csla.DataPortalException: DataPortal.Fetch failed (Logon ERROR: current logon ticket is not valid.) ---> Csla.Reflection.CallMethodException: ReviewSetsList.DataPortal_Fetch method call failed ---> System.Exception: Logon ERROR: current logon ticket is not valid.
   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewSetsList.DataPortal_Fetch() in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewSetsList.cs:line 278
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   --- End of inner exception stack trace ---
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object criteria)
   at ERxWebClient2.Controllers.CodesetController.CodesetsByReview() in D:\Github\eppi\ERCentralAPI\ERxWebClient2\Controllers\CodesetController.cs:line 44
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

2018-10-03 17:40:15.144 +01:00 [ERR] An unhandled exception has occurred while executing the request
System.Exception: Logon ERROR: current logon ticket is not valid.
   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at ERxWebClient2.Controllers.ReviewStatisticsController.ExcecuteReviewStatisticsCountCommand() in D:\Github\eppi\ERCentralAPI\ERxWebClient2\Controllers\ReviewStatisticsController.cs:line 52
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
2018-10-03 17:40:15.144 +01:00 [ERR] Fetching criteria: ""
Csla.DataPortalException: DataPortal.Fetch failed (Logon ERROR: current logon ticket is not valid.) ---> Csla.Reflection.CallMethodException: ReviewStatisticsCodeSetList.DataPortal_Fetch method call failed ---> System.Exception: Logon ERROR: current logon ticket is not valid.
   at BusinessLibrary.Security.ReviewerIdentity.get_ReviewId() in D:\Github\eppi\EPPIReviewer4.2015\Server\Security\ReviewerIdentity.cs:line 79
   at BusinessLibrary.BusinessClasses.ReviewStatisticsCodeSetList.FillList(Boolean IsCompleted) in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewStatisticsCodeSetList.cs:line 56
   at BusinessLibrary.BusinessClasses.ReviewStatisticsCodeSetList.DataPortal_Fetch(SingleCriteria`2 criteria) in D:\Github\eppi\EPPIReviewer4.2015\Server\BusinessClasses\ReviewStatisticsCodeSetList.cs:line 39
   at lambda_method(Closure , Object , Object[] )
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   --- End of inner exception stack trace ---
   at Csla.Reflection.MethodCaller.CallMethod(Object obj, DynamicMethodHandle methodHandle, Boolean hasParameters, Object[] parameters)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.MethodCaller.<CallMethodTryAsync>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Reflection.LateBoundObject.<CallMethodTryAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Csla.Server.SimpleDataPortal.<Fetch>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at Csla.DataPortal`1.Fetch(Type objectType, Object criteria)
   at Csla.DataPortal`1.Fetch(Object criteria)
   at ERxWebClient2.Controllers.ReviewStatisticsController.FetchCounts(SingleCriteria`1 crit) in D:\Github\eppi\ERCentralAPI\ERxWebClient2\Controllers\ReviewStatisticsController.cs:line 68

2018-10-03 17:43:38.282 +01:00 [ERR] (node:11040) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
